# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

#required = ["gitlab.com/avokadoen/softsecoblig2/cmd/forum"]

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/microcosm-cc/bluemonday"
  version = "1.0.1"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.1"

[[constraint]]
  name = "gopkg.in/russross/blackfriday.v2"
  version = "2.0.1"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "gitlab.com/avokadoen/softsecoblig2"
  go-version = "1.11"
  install = [ "./..."]
  ensure = "false"
